### ISSUE TITLE
[HW] Sanskar Shukla

### ISSUE THREAD

**Issue by shuklajr** [datastaxdevs/workshop-graphql-netflix#102]
**Name:** Sanskar Shukla
**Email:** shuklajr231@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sanskar-shukla-6907611b2

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (114)](https://user-images.githubusercontent.com/81213413/121648073-b84e5f00-cab4-11eb-9f63-906c6893eff7.png)
![Screenshot (115)](https://user-images.githubusercontent.com/81213413/121648086-bab0b900-cab4-11eb-9589-5aab96342b1c.png)
![Screenshot (111)](https://user-images.githubusercontent.com/81213413/121648098-be444000-cab4-11eb-804a-ed6ed0c2775b.png)
![Screenshot (113)](https://user-images.githubusercontent.com/81213413/121648109-c1d7c700-cab4-11eb-85b9-9294bc0e3f05.png)

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/W0VwsKtFR5O0I1209VWaOg?identity__email=shuklajr231@gmail.com
