### ISSUE TITLE
Netlify [netflix clone]

### ISSUE THREAD

**Issue by Nivisha1182** [datastaxdevs/workshop-graphql-netflix#117]
**Name:** <Nivisha Kulshreshtha>
**Email:** <nivishakulshreshtha@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/nivisha-kulshreshtha-3722061b3
![env - workshop-graphql-netflix-me - Gitpod Code - Google Chrome 6_12_2021 8_03_49 PM](https://user-images.githubusercontent.com/74779849/121780740-5dedf500-cbbf-11eb-912d-746a2145f0d2.png)
![env - workshop-graphql-netflix-me - Gitpod Code - Google Chrome 6_12_2021 8_06_45 PM](https://user-images.githubusercontent.com/74779849/121780742-60504f00-cbbf-11eb-970d-cf7e829bfed9.png)
![env - workshop-graphql-netflix-me - Gitpod Code - Google Chrome 6_12_2021 8_07_41 PM](https://user-images.githubusercontent.com/74779849/121780744-62b2a900-cbbf-11eb-882a-ab7fbb24f5f6.png)
![env - workshop-graphql-netflix-me - Gitpod Code - Google Chrome 6_12_2021 8_27_30 PM](https://user-images.githubusercontent.com/74779849/121780746-63e3d600-cbbf-11eb-9e6a-2038f99d8e58.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_12_09 PM](https://user-images.githubusercontent.com/74779849/121780749-65150300-cbbf-11eb-83aa-bcaecb52f85a.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_12_35 PM](https://user-images.githubusercontent.com/74779849/121780752-67775d00-cbbf-11eb-814b-7e68d7da8907.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_13_26 PM](https://user-images.githubusercontent.com/74779849/121780754-69412080-cbbf-11eb-98f1-5c4e7a3ba948.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_22_16 PM](https://user-images.githubusercontent.com/74779849/121780756-6b0ae400-cbbf-11eb-9983-4dc4bf20aba5.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_23_52 PM](https://user-images.githubusercontent.com/74779849/121780758-6cd4a780-cbbf-11eb-92f8-73cddb8c7564.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_25_51 PM](https://user-images.githubusercontent.com/74779849/121780761-6e05d480-cbbf-11eb-8289-1553535f4f94.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_28_35 PM](https://user-images.githubusercontent.com/74779849/121780764-6f370180-cbbf-11eb-8eb7-884100e8b245.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_29_40 PM](https://user-images.githubusercontent.com/74779849/121780766-7100c500-cbbf-11eb-8473-cd54b5afeb93.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_30_46 PM](https://user-images.githubusercontent.com/74779849/121780772-75c57900-cbbf-11eb-9f99-ee0b47d3700b.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_40_05 PM](https://user-images.githubusercontent.com/74779849/121780786-7d851d80-cbbf-11eb-817a-d6173514106c.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_41_43 PM](https://user-images.githubusercontent.com/74779849/121780791-7fe77780-cbbf-11eb-9bcd-4bb288475e62.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_42_18 PM](https://user-images.githubusercontent.com/74779849/121780793-8249d180-cbbf-11eb-8d97-6dd20665ea2d.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_43_15 PM](https://user-images.githubusercontent.com/74779849/121780796-85dd5880-cbbf-11eb-993a-2023b3e31d95.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_48_22 PM](https://user-images.githubusercontent.com/74779849/121780798-883fb280-cbbf-11eb-98a0-769e2b72c8bd.png)
![Dashboard — DataStax Astra - Google Chrome 6_12_2021 7_50_11 PM](https://user-images.githubusercontent.com/74779849/121780801-9097ed80-cbbf-11eb-92f1-48adbd07f801.png)
![React App - Google Chrome 6_12_2021 8_36_13 PM](https://user-images.githubusercontent.com/74779849/121780806-968dce80-cbbf-11eb-8be7-d8d83a002094.png)
![React App - Google Chrome 6_12_2021 8_36_34 PM](https://user-images.githubusercontent.com/74779849/121780823-ad342580-cbbf-11eb-898d-12182e53e550.png)

>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Hey seems like you successfully deploy the application congratulations

Could you also insert one of your movie in the db please and share a screenshot ?
 
You can find instructions are on step7 and you can also check others homework submissions for ideas.
