### ISSUE TITLE
[HW] K S A R AMBEDKAR

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-graphql-netflix#126]
**Name:** K S A R AMBEDKAR
**Email:** ambedkar1985@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/k-s-a-r-ambedkar-50b12088/

Attach the homework screenshots below:
[[HW]-Assign . of Netflix live.pdf](https://github.com/datastaxdevs/workshop-graphql-netflix/files/6643702/HW.-Assign.of.Netflix.live.pdf)

**Comment by clun** [comment]
duplicate of the #125 will just close this one
