### ISSUE TITLE
[HW] Nurun Nahar Ity

### ISSUE THREAD

**Issue by nni-fi** [datastaxdevs/workshop-graphql-netflix#127]
**Name:** Nurun Nahar Ity
**Email:** itybd@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/itynurun/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

<img src="https://user-images.githubusercontent.com/81568975/121911545-864d2f00-cd38-11eb-9d6d-8ccfe541c852.PNG" />

<img src="https://user-images.githubusercontent.com/81568975/121911546-864d2f00-cd38-11eb-8a82-e204b17ec6d5.PNG" />

<img src="https://user-images.githubusercontent.com/81568975/121911530-82b9a800-cd38-11eb-8452-c302bb221cc1.PNG" />

<img src="https://user-images.githubusercontent.com/81568975/121911974-da581380-cd38-11eb-85b6-a12ce89a3dd4.PNG" />

<img src="https://user-images.githubusercontent.com/81568975/121912933-a6312280-cd39-11eb-9b95-16b5b4b621da.jpg" />

**Comment by clun** [comment]
Castle in the sky is such a masterpiece

Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/rF7KciAlT9q1cfT1XKG0uw?identity__email=itybd@hotmail.com

**Comment by nni-fi** [comment]
Thanks, Cedric! :)
