### ISSUE TITLE
[HW] Arinjay Gangwar

### ISSUE THREAD

**Issue by arinjayg** [datastaxdevs/workshop-graphql-netflix#137]
**Name:** Arinjay Gangwar
**Email:** <arinjay.gangwar100@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/arinjay-gangwar-1a3b93166

![Screenshot 2021-06-16 095323_LI](https://user-images.githubusercontent.com/76163860/122158055-9aed0c80-ce89-11eb-93ce-40a36a4c38ab.jpg)

![Screenshot 2021-06-16 095253](https://user-images.githubusercontent.com/76163860/122158079-a3ddde00-ce89-11eb-9a0b-d292ab1ec8be.jpg)

![Screenshot 2021-06-16 095233](https://user-images.githubusercontent.com/76163860/122158099-af310980-ce89-11eb-868d-e886106fcf68.jpg)

**Comment by clun** [comment]
Great job, congratulations.

Here is your badge
https://api.badgr.io/public/assertions/XouI1XzxQHytKKM3aRapvQ?identity__email=arinjay.gangwar100%40gmail.com
