### ISSUE TITLE
Netflix-Clone Rohan Goyal

### ISSUE THREAD

**Issue by 37rohan** [datastaxdevs/workshop-graphql-netflix#168]
**Name:** Rohan Goyal
**Email:** rohangoyal264@gmail.com
**Linkedin Profile:** [Linkedin Profile](https://www.linkedin.com/in/rohan-goyal-3a1744200/)

Attach the homework screenshots below:
-----------------------------------------
![Screenshot_1](https://user-images.githubusercontent.com/76154317/124008745-61281400-d9fa-11eb-98da-994fe134e379.png)

![Screenshot_2](https://user-images.githubusercontent.com/76154317/124008767-671df500-d9fa-11eb-85e8-091de18d5d1f.png)

![Screenshot_3](https://user-images.githubusercontent.com/76154317/124008785-6e450300-d9fa-11eb-91be-db180c5555e2.png)

![Screenshot_4](https://user-images.githubusercontent.com/76154317/124008817-7b61f200-d9fa-11eb-8a71-a89344354e64.png)

![Screenshot_5](https://user-images.githubusercontent.com/76154317/124008679-4f467100-d9fa-11eb-892b-09d2da4ab605.png)

![Screenshot_6](https://user-images.githubusercontent.com/76154317/124008700-55d4e880-d9fa-11eb-8734-5c8e7a8d286b.png)

![Screenshot_7](https://user-images.githubusercontent.com/76154317/124008714-5a010600-d9fa-11eb-967a-53338ab49494.png)

**Comment by SonicDMG** [comment]
Hi there Rohan, thank you for your submission. All looks good except I don't see a video that you inserted per step 2 in the homework.
2. Insert a movie of your choice in the database.

Please insert a video of your own and include a screenshot. Thank you.

**Comment by 37rohan** [comment]
Hello sir,  i've to add a single movie clip in this??

**Comment by 37rohan** [comment]
Sir i updated and now i added a movie named Iron Man 3

![Screenshot_11](https://user-images.githubusercontent.com/76154317/124353651-6917cc00-dc25-11eb-83b8-dfea6b623db2.png)

**Comment by 37rohan** [comment]
> Hi there Rohan, thank you for your submission. All looks good except I don't see a video that you inserted per step 2 in the homework.
> 2. Insert a movie of your choice in the database.
> 
> Please insert a video of your own and include a screenshot. Thank you.

Sir i updated and now i added a movie named Iron Man 3

![Screenshot_11](https://user-images.githubusercontent.com/76154317/124353651-6917cc00-dc25-11eb-83b8-dfea6b623db2.png)

**Comment by SonicDMG** [comment]
Perfect, thank you. Thanks for following up as well. Here you go -> https://api.badgr.io/public/assertions/uGXoEW3KRhK7emHbMNBpfg?identity__email=rohangoyal264%40gmail.com

**Comment by 37rohan** [comment]
# Thank you sir
