### ISSUE TITLE
[HW] Abhay Khosla Netflix Clone Badge 

### ISSUE THREAD

**Issue by Abhay2412** [datastaxdevs/workshop-graphql-netflix#171]
**Name:** Abhay Khosla
**Email:** abhaykhosla0@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhaykhosla/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
**_2. Insert a movie of your choice in the database_**
The new movie Deadpool 2 added into the Netflix Clone:
![New Movie Screenshot](https://user-images.githubusercontent.com/57297897/124010288-e16b5c80-d99b-11eb-8fea-062a909bfa9e.png)

**_3. Make screenshots alongside the steps and show us your deployed production Netflix clone up in Netlify._**

4. Install the Netlify CLI (Command Line Interface)
The screenshot of it installed on GitPod: 
![Step 4](https://user-images.githubusercontent.com/57297897/124011043-cea55780-d99c-11eb-9ac8-ece20d101964.png)
5. Not attaching the .env file due to security issues as mentioned in the livestream
6. Configure Environment Variables and Install Dependencies
Screenshot of installing the dependencies: 
![Step 6](https://user-images.githubusercontent.com/57297897/124011647-7a4ea780-d99d-11eb-8b6c-cfaa3061438c.png)
7. Launch your app
Message showing successful deployment server screenshot:
![Step 7](https://user-images.githubusercontent.com/57297897/124011967-d3b6d680-d99d-11eb-8fb0-6ceb7821ae9b.png)
Screenshot of the preview pane:
![Preview Pane](https://user-images.githubusercontent.com/57297897/124012041-e8936a00-d99d-11eb-8e7b-dcf9f081145a.png)
8. Connect Netlify to your site
Screenshot of me running the logout command first and then running the login command:
![Logout and Login](https://user-images.githubusercontent.com/57297897/124012261-35774080-d99e-11eb-8189-d298296f13ee.png)
Had to press Ctrl+C screenshot:
![Terminate Login](https://user-images.githubusercontent.com/57297897/124012389-593a8680-d99e-11eb-8e82-44f4bb311d4c.png)
Netlify Authorize Screenshot:
![Authorize Screen](https://user-images.githubusercontent.com/57297897/124012510-77a08200-d99e-11eb-96a4-1b89bef25080.png)
Authorize Granted Screenshot:
![Authorize Granted](https://user-images.githubusercontent.com/57297897/124012612-943cba00-d99e-11eb-87b0-31e1b2a04ace.png)
Netlify is linked to my workspace screenshot:
![Link Netlify](https://user-images.githubusercontent.com/57297897/124012783-c5b58580-d99e-11eb-86c3-09b7b1bef66d.png)
Not providing the screenshot for this command netlify env:import .env

9. Deploy to production
Successful completion of build command 
![Build Command](https://user-images.githubusercontent.com/57297897/124013087-1cbb5a80-d99f-11eb-9f07-40d585a14dcc.png)
Completion of deploy command
![Deploy Command](https://user-images.githubusercontent.com/57297897/124013213-44122780-d99f-11eb-9cca-3c567a3775c6.png)
Final Image of the Clone:
![Final Clone](https://user-images.githubusercontent.com/57297897/124013407-7d4a9780-d99f-11eb-8d74-73808e282260.png)

Link to the Netflix Clone:
https://elegant-jepsen-b864df.netlify.app/

**Comment by SonicDMG** [comment]
Excellent job all around Abhay. Thank you for not posting your Astra token and adding a video of your own. Here's your badge -> https://api.badgr.io/public/assertions/QPc0fRz3QviVcK7H2DI6Ew?identity__email=abhaykhosla0%40gmail.com

**Comment by Abhay2412** [comment]
Thanks David for the workshop!
