### ISSUE TITLE
[HW] Chandan Mishra

### ISSUE THREAD

**Issue by MishraCh** [datastaxdevs/workshop-graphql-netflix#179]
**Name:** Chandan Mishra
**Email:** Chandanmshr2712gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/chandan-mishra-pec/

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/35769961/124016673-88cfaa00-da03-11eb-8879-5286bda8e278.png)

**Comment by SonicDMG** [comment]
Ok, I see, looks like you created another issue with the image embedded this time. Either one works and since I already commented on the other one I will close this as a duplicate. https://github.com/datastaxdevs/workshop-graphql-netflix/issues/178
