### ISSUE TITLE
[HW] Nidhi Sabu

### ISSUE THREAD

**Issue by blurryface-1** [datastaxdevs/workshop-graphql-netflix#194]
**Name:** Nidhi Sabu
**Email:** nidhisabu332@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nidhi-sabu/
**Link:** https://modest-newton-3c7f08.netlify.app/

Attach the homework screenshots below:
-----------------------------------------

### Standard preview:
![image](https://i.ibb.co/nCSPzcL/web-prev1.jpg)
<br>
![image](https://i.ibb.co/CB74sKZ/website1.jpg)
<hr>

### After adding a movie *(Interstellar)* to the database:
**Interstellar Preview 1:**
![image](https://i.ibb.co/qDtpy9Y/movie-prev1.jpg)
<br>
**Interstellar Preview 2:**
![image](https://i.ibb.co/jkpvpPL/movie-prev2.jpg)
<hr>

### Changing the cover movie to Interstellar: 
![image](https://i.ibb.co/JkpZxjn/changed-covermovie.jpg)

**Adding:**
![image](https://i.ibb.co/sv6L7T7/add-movie.jpg)
<hr>

### AstraDB Dashboard:
![image](https://i.ibb.co/cvMsSST/astra-dashboard.jpg)
<hr>

### AstraDB Playground:
**graphql-schema:**
![image](https://i.ibb.co/C2s4N0R/Picture1.jpg)

**graphql:**
![image](https://i.ibb.co/xFT6X6F/graphql.jpg)
<hr>

### Netlify:
**site overview:**
![image](https://i.ibb.co/12Mkm1p/netlify-siteoverview.jpg)

**authorize page:**
![image](https://i.ibb.co/S5PWC39/authorize.jpg)
<hr>

### GitHub Repository:
![image](https://i.ibb.co/hF8mbHx/github-repo.jpg)
<hr>

### Gitpod IDE:
![image](https://i.ibb.co/9qstDtQ/gitpod.jpg)

**Create .env file:**
-- image removed by team --

**Deploy build**
![image](https://i.ibb.co/HxSD1Xf/deploy.jpg)
<hr>

**Comment by SonicDMG** [comment]
Excellent work Nidhi, thank you. Here's your badge -> https://api.badgr.io/public/assertions/C7u6zeXnTqKrP6ofj4pgqg?identity__email=nidhisabu332%40gmail.com

**Comment by SonicDMG** [comment]
I also had to remove one of your images because it contained your Astra token. Please delete your token to ensure no security issues.
