### ISSUE TITLE
[HW] <Puru>

### ISSUE THREAD

**Issue by Puru-Soni** [datastaxdevs/workshop-graphql-netflix#222]
**Name:** Puru
**Email:** puru20010105@gmail.com
**Linkedin Profile:** www.linkedin.com/in/puru-soni-646188205

Attach the homework screenshots below:
-----------------------------------------
https://nervous-shirley-16c60d.netlify.app/

![app](https://user-images.githubusercontent.com/74522965/124168065-44571380-dac2-11eb-910e-188aeb859872.jpg)

**Comment by SonicDMG** [comment]
Hi there Puru, thank you for your submission. All looks good except I don't see a video that you inserted per step 2 in the homework.
2. Insert a movie of your choice in the database.

Please insert a video of your own and include a screenshot. Thank you.
