### ISSUE TITLE
[HW] Vatsavaya Sampath

### ISSUE THREAD

**Issue by Sampath-Vatsavaya** [datastaxdevs/workshop-graphql-netflix#256]
**Name:** Vatsavaya Sampath
**Email:** vatsavaya.sampath@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vatsavaya-sampath/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![hw1](https://user-images.githubusercontent.com/84452919/124349714-4c23ce80-dc0e-11eb-883e-32c3e9fdb4f7.PNG)

![hw2](https://user-images.githubusercontent.com/84452919/124349720-51811900-dc0e-11eb-8fcc-dede3b927b1f.PNG)

![hw1 5](https://user-images.githubusercontent.com/84452919/124349722-5645cd00-dc0e-11eb-8b43-9108f179ddab.PNG)

![hw3](https://user-images.githubusercontent.com/84452919/124349726-5a71ea80-dc0e-11eb-8d5a-42cd460b0cc9.PNG)

![hw4](https://user-images.githubusercontent.com/84452919/124349729-5d6cdb00-dc0e-11eb-8858-e03ce3030a76.PNG)

![hw5](https://user-images.githubusercontent.com/84452919/124349737-61006200-dc0e-11eb-810b-074e2e92a9e4.PNG)

![hw8](https://user-images.githubusercontent.com/84452919/124349753-6b226080-dc0e-11eb-879a-c280e9a591c9.PNG)

**Comment by clun** [comment]
Really cool

**Comment by HadesArchitect** [comment]
Hey **Vatsavaya Sampath**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/oYtkNvqHRjyPPbcxYSnAAQ
