### ISSUE TITLE
[HW] Subha_Ranjan_Das

### ISSUE THREAD

**Issue by Subha-Ranjan-Das** [datastaxdevs/workshop-graphql-netflix#259]
**Name:** Subha_Ranjan_Das
**Email:** subhadas201201@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

![Screenshot (99)](https://user-images.githubusercontent.com/86057597/124355377-67063b00-dc2e-11eb-81c9-f50b33d6f80f.png)
![Screenshot (100)](https://user-images.githubusercontent.com/86057597/124355380-6a012b80-dc2e-11eb-8913-97758af90856.png)
![Screenshot (98)](https://user-images.githubusercontent.com/86057597/124355384-6bcaef00-dc2e-11eb-802b-c09675ae6f88.png)

**Comment by SonicDMG** [comment]
Ok, I see your custom video and I will add the credit to your original submission and close this one out. Thank you.
