### ISSUE TITLE
[HW] Anshul verma

### ISSUE THREAD

**Issue by vermaanshul117** [datastaxdevs/workshop-graphql-netflix#263]
**Name:** Anshul verma
**Email:** vermaanshul6925@gmail.com

![Screenshot (2)](https://user-images.githubusercontent.com/86737701/124361266-d50d2b00-dc4b-11eb-8cfc-8d59e0e46e35.png)

![hm_1](https://user-images.githubusercontent.com/86737701/124361200-7b0c6580-dc4b-11eb-9c32-52f9a20057ad.PNG)

![hm1](https://user-images.githubusercontent.com/86737701/124361262-cb83c300-dc4b-11eb-881c-7e9fb78151ff.PNG)
>
**Linkedin Profile:** <LINK>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Duplicate ? will close this one
