### ISSUE TITLE
[HW] Pranjul Yaduvanshi

### ISSUE THREAD

**Issue by iampranjul** [datastaxdevs/workshop-graphql-netflix#265]
**Name:** Pranjul Yaduvanshi 
**Email:** py2000boy@gmail.com 
**Linkedin Profile:** https://www.linkedin.com/in/pranjulyaduvanshi/

Attach the homework screenshots below:
Added Fast and Furious 9 Movie
-----------------------------------------
![Screenshot 2021-07-03 224046](https://user-images.githubusercontent.com/56435620/124362465-a777b000-dc52-11eb-8b56-59c4ada668c5.png)
![Screenshot 2021-07-03 230212](https://user-images.githubusercontent.com/56435620/124362481-be1e0700-dc52-11eb-9bed-59cff4940d85.png)

<SCREENSHOTS>
https://compassionate-bhabha-a52169.netlify.app/

**Comment by HadesArchitect** [comment]
Hey **Pranjul Yaduvanshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8iVFOsRZRUCk-fSTfu53FQ

**Comment by iampranjul** [comment]
> Hey **Pranjul Yaduvanshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8iVFOsRZRUCk-fSTfu53FQ

Thank you :)
