### ISSUE TITLE
[HW] May Borkowicz

### ISSUE THREAD

**Issue by ashbork** [datastaxdevs/workshop-graphql-netflix#313]
**Name:** May Borkowicz
**Email:** maybork@pm.me
**Linkedin Profile:** x

Here's my repo: https://gitlab.com/maybork/appdev-week3-graphql
And that's the netlify app if you wanna check the result (it's in the Anime section): https://elated-liskov-ee57bf.netlify.app/
Attach the homework screenshots below:
-----------------------------------------
![thumbnail_refers_to](https://user-images.githubusercontent.com/82605611/126524962-05f360d8-b79d-4056-adcf-d208e1d3ee71.png)
![movie_insert](https://user-images.githubusercontent.com/82605611/126524972-a07d840f-74cb-4204-8446-118dd16a75a1.png)
![final_result](https://user-images.githubusercontent.com/82605611/126524976-c29682dd-bf11-43c6-be6e-9afbc0040fda.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **May Borkowicz**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EnM8-2XHQxaTA-MdpwqxtQ
