### ISSUE TITLE
[HW] Oleksandr V | Imported movie & deployed app | Homework screenshots

### ISSUE THREAD

**Issue by volyanyk** [datastaxdevs/workshop-graphql-netflix#318]
**Name:** Oleksandr V
**Email:** Oleksandr.Volyanyk@gmail.com
**Linkedin Profile:** /in/oleksandr-volyanyk/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>
![result](https://user-images.githubusercontent.com/19517331/126529921-103bd74d-c2b5-4aad-874b-a462bb0fcb16.png)
![build](https://user-images.githubusercontent.com/19517331/126529927-3e8b8909-00dc-4dd0-b481-c36300e9c332.png)
![deploy](https://user-images.githubusercontent.com/19517331/126529929-208a7b33-40ad-4ee9-ba73-cacc4e211ea6.png)
![npmInstall](https://user-images.githubusercontent.com/19517331/126529934-74d39141-4a88-4ef8-b937-a6383cde72b0.png)
![hw](https://user-images.githubusercontent.com/19517331/126530572-bfc8abe2-5db1-479b-9f8b-67be21122edf.png)

**Comment by HadesArchitect** [comment]
Hey **Oleksandr V**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/jz2pJu0zTZ6-BYvc9q7how
