### ISSUE TITLE
[HW] <K Tejeshwar Reddy>

### ISSUE THREAD

**Issue by rktejesh** [datastaxdevs/workshop-graphql-netflix#32]
![image](https://user-images.githubusercontent.com/73354337/121416776-d158f200-c986-11eb-8662-ecd891681481.png)
![image](https://user-images.githubusercontent.com/73354337/121417054-1d0b9b80-c987-11eb-8cde-5efdfad82694.png)
![image](https://user-images.githubusercontent.com/73354337/121417253-517f5780-c987-11eb-9df0-a5cf8df4299b.png)
![image](https://user-images.githubusercontent.com/73354337/121417356-6f4cbc80-c987-11eb-9b3e-7306804ff0b2.png)

**Comment by clun** [comment]
Great job ! Here is your badge
