### ISSUE TITLE
[HW] OĞUZHAN NEJAT KARABAŞ / karabasnejat@hotmail.com

### ISSUE THREAD

**Issue by karabasnejat** [datastaxdevs/workshop-graphql-netflix#35]
![Playground](https://user-images.githubusercontent.com/62561906/121418302-7b2e8380-c973-11eb-99d5-34cb177851b4.png)

![Interstellar](https://user-images.githubusercontent.com/62561906/121418322-808bce00-c973-11eb-8094-b5a4f1047b53.png)

![React](https://user-images.githubusercontent.com/62561906/121419580-c8f7bb80-c974-11eb-9dca-3df8c3870546.png)

mail address : karabasnejat@hotmail.com
Today I attented the Netflix workshop and it was truly great. I learned a lot of stuff. As you clarified for us to get a certificate, I add my own movie " Interstellar" and I also create a thumbnail for the movie. I hope I get my certificate.

**Comment by karabasnejat** [comment]
@HadesArchitect I completed the task. Do let me know if anything is missing.

**Comment by clun** [comment]
Thank you very much for the work ! We needed a few days to review all your submissions we doo have a lot of students

Here is you badge, glad you like the session.

https://badgr.com/issuers/60646434ed41196788203389/badges/60bdeec101c5e35a4ad6dffc/assertions/60c738088f65b21516e88cef
