### ISSUE TITLE
[HW] Kaveri Pandey

### ISSUE THREAD

**Issue by kaveripandey** [datastaxdevs/workshop-graphql-netflix#41]
Netlify link- https://goofy-franklin-2bd791.netlify.app
My email id for the badge is kaveriipandeyy@gmail.com
These are the screenshots of my Netflix clone running on Netlify.
![Screenshot 2021-06-10 024008](https://user-images.githubusercontent.com/83645105/121430462-bfcb1680-c995-11eb-8838-91c7a6f323c5.png)
![Screenshot 2021-06-10 023926](https://user-images.githubusercontent.com/83645105/121430494-cce80580-c995-11eb-93d1-3c67e55c607c.png)
![Screenshot 2021-06-10 025707](https://user-images.githubusercontent.com/83645105/121431892-a034ed80-c997-11eb-9be6-3c6204a61490.png)

I added the movie - "Butterfly Effect" with the thumbnail of another movie.
![Screenshot 2021-06-10 023822](https://user-images.githubusercontent.com/83645105/121430503-d07b8c80-c995-11eb-9ced-26998eb2eaff.png)

It was indeed a great session. I learned so many new things.
Thank you,
Kaveri

**Comment by kaveripandey** [comment]
@HadesArchitect @RyanWelford @SonicDMG

**Comment by clun** [comment]
Great job here is your badge
https://badgr.com/issuers/60646434ed41196788203389/badges/60bdeec101c5e35a4ad6dffc/assertions/60c7402933d5df655e4dd17d
