### ISSUE TITLE
[HW] Chandan H- Week 3 - Netflix Clone

### ISSUE THREAD

**Issue by Chandan-Hemraj** [datastaxdevs/workshop-graphql-netflix#411]
**Name:** Chandan H
**Email:** chandanhemraj99@gmail.com
**Linkedin Profile:** [https://www.linkedin.com/in/chandan-h-6142b2199/](url)

Attach the homework screenshots below:
-----------------------------------------

![Screenshot (434)](https://user-images.githubusercontent.com/87279692/126789286-0eac46bc-b705-43fb-84dc-c837b8435861.png)

![Screenshot (435)](https://user-images.githubusercontent.com/87279692/126789320-94c62867-612c-4aaa-8bbb-93f0fe53e72b.png)

![Screenshot (436)](https://user-images.githubusercontent.com/87279692/126789358-3c33bf02-cb5e-4518-9d28-0ad178824891.png)

**Comment by hemidactylus** [comment]
Hi Chandan, nice job getting the app deployed. I don't see your custom video though on your site. Could you please add one and take a screenshot or just post your netlify link. If you did add one please point out which one. Thank you.
