### ISSUE TITLE
[HW] Pankaj Biradar

### ISSUE THREAD

**Issue by pankaj892** [datastaxdevs/workshop-graphql-netflix#483]
**Name:**  Pankaj Biradar
**Email:**  pankaj28988@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pankaj-biradar/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![graphql](https://user-images.githubusercontent.com/31444506/127769531-965fe3e4-928f-44b3-a7a0-c9d6d44bbd77.jpg)

![netflix3](https://user-images.githubusercontent.com/31444506/127769522-263e705a-670e-46ef-a7e8-46d07ae40281.jpg)

![Netflix](https://user-images.githubusercontent.com/31444506/127769499-27c0f9cc-24ee-4c3d-b10b-67490e8490ae.jpg)

![Netflix1](https://user-images.githubusercontent.com/31444506/127769502-13f4aad9-7346-47ec-9dc8-19c288de7afb.jpg)

**Comment by HadesArchitect** [comment]
Hey **Pankaj Biradar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/s3-uj17URg6XhNpu_7bp1w
