### ISSUE TITLE
[HW] Rahul Sunil

### ISSUE THREAD

**Issue by rahulsunil2** [datastaxdevs/workshop-graphql-netflix#51]
**Name:** Rahul Sunil

Hi,
I inserted a new movie into my database as per the homework requirements - **Edge of Tomorrow**. 
Attached are 2 screenshots (of the GraphQL mutation & result) & a screenshot of the updated Netlify Netflix Clone.

![graphQL-screens](https://user-images.githubusercontent.com/22911414/121466113-7e0d9080-c9d4-11eb-87d6-6ffdf365b784.png)
![netflix-screens](https://user-images.githubusercontent.com/22911414/121465906-1c4d2680-c9d4-11eb-97bb-60fe61405ad4.png)

**My GitHub Repo:** https://github.com/rahulsunil2/netflix-clone
**My Netlify Clone:** https://netflix-clone-graphql.netlify.app/

**Comment by rahulsunil2** [comment]
**Name:** Rahul Sunil
**Email:** rahulsunil2@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rahulsunil2/

## Attach the homework screenshots below:
![graphQL-screens](https://user-images.githubusercontent.com/22911414/121493679-afe31f00-c9f5-11eb-947e-1c3f849ec6ee.png)
![netflix-screens](https://user-images.githubusercontent.com/22911414/121493688-b1ace280-c9f5-11eb-83c5-227b01dfb034.png)

**Comment by RyanWelford** [comment]
Thanks Rahul! Looks great!

**Comment by rahulsunil2** [comment]
Thanks a lot, @RyanWelford ... Thanks for the session, It was a great session and I learned a lot of new things that I can use in my future projects.

**Comment by clun** [comment]
Here is your badge sir
https://badgr.com/issuers/60646434ed41196788203389/badges/60bdeec101c5e35a4ad6dffc/assertions/60c7473201c5e35a4ad979dc
