### ISSUE TITLE
[HW] Rahul Sunil

### ISSUE THREAD

**Issue by rahulsunil2** [datastaxdevs/workshop-graphql-netflix#74]
**Name:** Rahul Sunil
**Email:** rahulsunil2@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rahulsunil2/

Attach the homework screenshots below:
-----------------------------------------

![graphQL-screens](https://user-images.githubusercontent.com/22911414/121493679-afe31f00-c9f5-11eb-947e-1c3f849ec6ee.png)
![netflix-screens](https://user-images.githubusercontent.com/22911414/121493688-b1ace280-c9f5-11eb-83c5-227b01dfb034.png)

**Comment by clun** [comment]
Great job ! Thank you 

Here is your job:
https://badgr.com/public/assertions/noBZgiscQv-SEw_qrn58rg?identity__email=rahulsunil2@gmail.com
