### ISSUE TITLE
[HW] Abhinav Kushagra

### ISSUE THREAD

**Issue by abhinavkushagra** [datastaxdevs/workshop-graphql-netflix#93]
**Name:** Abhinav Kushagra
**Email:** abhinavkushagra@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhinavkushagra/

Attach the homework screenshots below:
-----------------------------------------
I added Whiplash in the movies under Drama genre and the output is as expected. Below are the steps I followed. 

Step I. 
![image](https://user-images.githubusercontent.com/17827196/121568481-5ef71900-ca3d-11eb-8674-202ec902696d.png)

Step II. 
![image](https://user-images.githubusercontent.com/17827196/121568570-73d3ac80-ca3d-11eb-9e61-52a4d359ba2f.png)

Step III.
![image](https://user-images.githubusercontent.com/17827196/121568599-7c2be780-ca3d-11eb-9800-1be29c9ceed5.png)

Step IV. 
![image](https://user-images.githubusercontent.com/17827196/121568628-8352f580-ca3d-11eb-963f-d21102131b39.png)

Step V.
![image](https://user-images.githubusercontent.com/17827196/121568692-95cd2f00-ca3d-11eb-8a00-d6e0c2c125db.png)

Step VI. (Final)  - Users can see Whiplash movie on the Netflix clone page.
![image](https://user-images.githubusercontent.com/17827196/121568722-9d8cd380-ca3d-11eb-8346-710219f73480.png)

**Comment by clun** [comment]
Great Job, thank you for your work. Whiplash is such a masterpiece.

Here is your badge:
https://badgr.com/public/assertions/RuvEuU_kR6y27pC3fou5IQ?identity__email=abhinavkushagra@gmail.com

**Comment by abhinavkushagra** [comment]
Thanks a lot Cedrick! You guys are awesome. 
Also wanted to thank to the awesome team.
